import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './playwright-tests',
  timeout: 30_000,
  use: {
    baseURL: 'https://localhost:3000',
    // Accept the self-signed certificate generated by next dev --experimental-https
    ignoreHTTPSErrors: true,
    screenshot: 'on',
    video: 'off',
  },
  projects: [
    {
      name: 'desktop-chrome',
      use: { ...devices['Desktop Chrome'], viewport: { width: 1280, height: 800 } },
    },
    {
      name: 'mobile-chrome',
      use: { ...devices['Pixel 5'], viewport: { width: 393, height: 851 } },
    },
  ],
  reporter: [['list'], ['html', { outputFolder: 'playwright-tests/report', open: 'never' }]],
});
