import { defineConfig, devices } from '@playwright/test'

// Base URL is configurable so the suite can run against a local dev server
// (default) or any published/staging site. Set PLAYWRIGHT_BASE_URL to override,
// e.g. PLAYWRIGHT_BASE_URL=https://example.com npx playwright test
const BASE_URL = process.env.PLAYWRIGHT_BASE_URL ?? 'https://localhost:3000'

// Only manage a local dev server when targeting localhost. When pointed at an
// external/published URL, skip starting (and waiting on) a local server.
const isLocal = /localhost|127\.0\.0\.1/.test(BASE_URL)

const isCI = !!process.env.CI

export default defineConfig({
  testDir: './playwright-tests',
  timeout: 30_000,
  globalSetup: './playwright-tests/global-setup.ts',
  // A stray `test.only` would silently shrink the blocking set in CI.
  forbidOnly: isCI,
  // Flakes are quarantined into the advisory lane, never retried into green.
  retries: 0,
  // GitHub-hosted runners have 4 vCPUs and each worker drives a browser.
  workers: isCI ? 2 : undefined,
  webServer: isLocal
    ? {
        // CI exercises the production build, which is the only mode that runs
        // the Cache Components prerender path the deployed site uses.
        command: isCI ? 'npm run start:e2e' : 'npm run dev',
        // Probe the storefront root: it renders the catalog, so a failed
        // migration or seed times out here rather than passing vacuously.
        url: `${BASE_URL}/`,
        // Reusing a server in CI would silently test a stale build.
        reuseExistingServer: !isCI,
        timeout: 120_000,
        // Accept the self-signed certificate generated by next dev --experimental-https
        ignoreHTTPSErrors: true,
      }
    : undefined,
  use: {
    baseURL: BASE_URL,
    // Accept the self-signed certificate generated by next dev --experimental-https
    ignoreHTTPSErrors: true,
    screenshot: 'only-on-failure',
    trace: 'retain-on-failure',
    video: 'off',
  },
  projects: [
    {
      name: 'desktop-chrome',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: '**/ux-audit.spec.ts',
    },
    {
      name: 'mobile-chrome',
      use: { ...devices['Pixel 5'], viewport: { width: 393, height: 851 } },
      testMatch: '**/ux-audit.spec.ts',
    },
    // UX screenshot audit over admin routes — advisory, authenticated. Kept in
    // its own projects so no project mixes blocking and advisory spec files.
    {
      name: 'ux-audit-admin-desktop',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: '**/ux-audit.spec.ts',
    },
    {
      name: 'ux-audit-admin-mobile',
      use: {
        ...devices['Pixel 5'],
        viewport: { width: 393, height: 851 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: '**/ux-audit.spec.ts',
    },
    // Product assistant regression — public desktop coverage.
    {
      name: 'ai-stock-privacy',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: '**/ai-stock-privacy.spec.ts',
    },
    // Order summaries — authenticated desktop coverage.
    {
      name: 'orders-list',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: '**/orders-list.spec.ts',
    },
    // Current platform capabilities — PWA, localization, discovery, and admin operations.
    {
      name: 'latest-features',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: '**/latest-features.spec.ts',
    },
    // Password validation — desktop
    {
      name: 'password-validation-desktop',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: '**/password-validation.spec.ts',
    },
    // Account page password validation — authenticated admin session (desktop)
    {
      name: 'account-password-validation',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: '**/account-password-validation.spec.ts',
    },
    // Admin views — authenticated admin session (desktop)
    {
      name: 'admin-desktop',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: '**/admin-views.spec.ts',
    },
    // Admin views — authenticated admin session (mobile)
    {
      name: 'admin-mobile',
      use: {
        ...devices['Pixel 5'],
        viewport: { width: 393, height: 851 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: '**/admin-views.spec.ts',
    },
    // Cart tests — authenticated admin session (desktop)
    {
      name: 'cart',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: [
        '**/cart.spec.ts',
        '**/checkout-error-recovery.spec.ts',
        '**/checkout-policy.spec.ts',
      ],
    },
    // Accessibility — public pages (unauthenticated, desktop)
    {
      name: 'accessibility-public',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: '**/accessibility.spec.ts',
      grep: /public pages/,
    },
    // Accessibility — authenticated pages (admin session, desktop)
    {
      name: 'accessibility-authenticated',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: '**/accessibility.spec.ts',
      grep: /authenticated pages/,
    },
    // Live orders E2E — authenticated, hits real database (no mocking)
    {
      name: 'orders-live',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: '**/orders-live.spec.ts',
    },
    // Product navigation regression — public, unauthenticated. Exercises the
    // client-side router.push() navigations (search dropdown, shop filters)
    // that previously navigated to non-localized /products/<id> URLs and 404'd.
    {
      name: 'product-navigation',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: '**/product-navigation.spec.ts',
    },
    // Public page coverage smoke — public, unauthenticated. Visits every public
    // route and asserts no HTTP error and no 404 body.
    {
      name: 'public-pages',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: '**/public-pages.spec.ts',
    },
    // Session isolation — manages its own browser contexts (one authenticated
    // from the stored state, one anonymous), so no storageState is set here.
    {
      name: 'session-isolation',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: '**/session-isolation.spec.ts',
    },
    // Variant options E2E — tests storefront + admin option manager
    {
      name: 'variant-options',
      timeout: 60000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: '**/variant-options.spec.ts',
    },
  ],
  reporter: isCI
    ? [
        ['github'],
        ['blob', { outputDir: 'playwright-tests/blob-report' }],
      ]
    : [
        ['list'],
        ['html', { outputFolder: 'playwright-tests/report', open: 'never' }],
      ],
})
