import { defineConfig, devices } from '@playwright/test'

// Base URL is configurable so the suite can run against a local dev server
// (default) or any published/staging site. Set PLAYWRIGHT_BASE_URL to override,
// e.g. PLAYWRIGHT_BASE_URL=https://example.com npx playwright test
const BASE_URL = process.env.PLAYWRIGHT_BASE_URL ?? 'https://localhost:3000'

// Only manage a local dev server when targeting localhost. When pointed at an
// external/published URL, skip starting (and waiting on) a local server.
const isLocal = /localhost|127\.0\.0\.1/.test(BASE_URL)

export default defineConfig({
  testDir: './playwright-tests',
  timeout: 30_000,
  globalSetup: './playwright-tests/global-setup.ts',
  webServer: isLocal
    ? {
        command: 'npm run dev',
        // Probe a route that returns 200 ('/' redirects/404s before a locale
        // prefix is applied), so reuseExistingServer detects a running server.
        url: `${BASE_URL}/en/shop`,
        // Always reuse an existing server (avoids cert issues with the
        // health-check poll and allows running 'npm run dev' externally before
        // the suite).
        reuseExistingServer: true,
        timeout: 120_000,
        // Accept the self-signed certificate generated by next dev --experimental-https
        ignoreHTTPSErrors: true,
      }
    : undefined,
  use: {
    baseURL: BASE_URL,
    // Accept the self-signed certificate generated by next dev --experimental-https
    ignoreHTTPSErrors: true,
    screenshot: 'only-on-failure',
    video: 'off',
  },
  projects: [
    {
      name: 'desktop-chrome',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: [
        '**/ui-changes.spec.ts',
        '**/fixed-background.spec.ts',
        '**/ux-audit.spec.ts',
        '**/orders-list.spec.ts',
        '**/ai-stock-privacy.spec.ts',
      ],
    },
    {
      name: 'mobile-chrome',
      use: { ...devices['Pixel 5'], viewport: { width: 393, height: 851 } },
      testMatch: [
        '**/ui-changes.spec.ts',
        '**/fixed-background.spec.ts',
        '**/ux-audit.spec.ts',
        '**/orders-list.spec.ts',
        '**/ai-stock-privacy.spec.ts',
      ],
    },
    // Password validation — desktop
    {
      name: 'password-validation-desktop',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: '**/password-validation.spec.ts',
    },
    // Account page password validation — authenticated admin session (desktop)
    {
      name: 'account-password-validation',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: '**/account-password-validation.spec.ts',
    },
    // Admin views — authenticated admin session (desktop)
    {
      name: 'admin-desktop',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: ['**/admin-views.spec.ts', '**/ux-audit.spec.ts'],
    },
    // Admin views — authenticated admin session (mobile)
    {
      name: 'admin-mobile',
      use: {
        ...devices['Pixel 5'],
        viewport: { width: 393, height: 851 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: ['**/admin-views.spec.ts', '**/ux-audit.spec.ts'],
    },
    // Cart tests — authenticated admin session (desktop)
    {
      name: 'cart',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: '**/cart.spec.ts',
    },
    // Accessibility — public pages (unauthenticated, desktop)
    {
      name: 'accessibility-public',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: '**/accessibility.spec.ts',
      grep: /public pages/,
    },
    // Accessibility — authenticated pages (admin session, desktop)
    {
      name: 'accessibility-authenticated',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: '**/accessibility.spec.ts',
      grep: /authenticated pages/,
    },
    // Live orders E2E — authenticated, hits real database (no mocking)
    {
      name: 'orders-live',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
        storageState: './playwright-tests/.auth/admin.json',
      },
      testMatch: '**/orders-live.spec.ts',
    },
    // Locale link smoke — public, unauthenticated. Guards against the
    // post-[locale]-migration regression where internal hrefs lost their
    // /{locale}/ prefix and 404'd.
    {
      name: 'locale-links',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: '**/locale-links.spec.ts',
    },
    // Product navigation regression — public, unauthenticated. Exercises the
    // client-side router.push() navigations (search dropdown, shop filters)
    // that previously navigated to non-localized /products/<id> URLs and 404'd.
    {
      name: 'product-navigation',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: '**/product-navigation.spec.ts',
    },
    // Public page coverage smoke — public, unauthenticated. Visits every public
    // route and asserts no HTTP error and no 404 body.
    {
      name: 'public-pages',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: '**/public-pages.spec.ts',
    },
    // Variant options E2E — tests storefront + admin option manager
    {
      name: 'variant-options',
      timeout: 60000,
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1280, height: 800 },
      },
      testMatch: '**/variant-options.spec.ts',
    },
  ],
  reporter: [
    ['list'],
    ['html', { outputFolder: 'playwright-tests/report', open: 'never' }],
  ],
})
