import { chromium } from '@playwright/test'
const b = await chromium.launch()
const c = await b.newContext({ baseURL: 'http://localhost:3000', ignoreHTTPSErrors: true })
const p = await c.newPage()
p.on('console', m => console.log('CONSOLE', m.type(), m.text()))
p.on('response', r => { if (r.url().includes('/api/auth')) console.log('RESP', r.status(), r.url()) })
await p.goto('/auth/signin')
await p.waitForSelector('input[name="identifier"]')
await p.fill('input[name="identifier"]', process.env.COPILOT_DEV_EMAIL)
await p.fill('input[type="password"], input[name="password"]', process.env.COPILOT_DEV_PASS)
await p.click('button[type="submit"]')
await p.waitForTimeout(6000)
console.log('URL', p.url())
console.log('TEXT', (await p.locator('body').innerText()).slice(0, 800))
await b.close()
