#!/usr/bin/env node
/**
 * generate-env.mjs
 *
 * Maps COPILOT_* environment variables → .env.local so the Next.js dev server
 * (and Playwright E2E tests) have everything they need when running inside a
 * GitHub Copilot agent session.
 *
 * Usage:
 *   node scripts/generate-env.mjs [--output .env.local]
 *
 * The script is intentionally idempotent: it only writes the file when at
 * least DATABASE_URL resolves to a non-empty value (meaning the Neon preview
 * branch has been created).  If DATABASE_URL cannot be resolved the script
 * exits with code 0 so the CI step doesn't fail — callers should check
 * whether .env.local was actually written.
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

const outputIndex = process.argv.indexOf("--output");
const outputPath = resolve(
  outputIndex !== -1 && process.argv[outputIndex + 1]
    ? process.argv[outputIndex + 1]
    : ".env.local",
);

// ---------------------------------------------------------------------------
// Variable map: [target key in .env.local, COPILOT_* source variable]
// ---------------------------------------------------------------------------
const VARIABLE_MAP = [
  ["DATABASE_URL", "COPILOT_DATABASE_URL"],
  ["UPSTASH_REDIS_REST_URL", "COPILOT_UPSTASH_REDIS_REST_URL"],
  ["UPSTASH_REDIS_REST_TOKEN", "COPILOT_UPSTASH_REDIS_REST_TOKEN"],
  ["UPSTASH_SEARCH_REST_URL", "COPILOT_UPSTASH_SEARCH_REST_URL"],
  ["UPSTASH_SEARCH_REST_TOKEN", "COPILOT_UPSTASH_SEARCH_REST_TOKEN"],
  [
    "UPSTASH_SEARCH_REST_READONLY_TOKEN",
    "COPILOT_UPSTASH_SEARCH_REST_READONLY_TOKEN",
  ],
  ["NEXT_PUBLIC_UPSTASH_SEARCH_REST_URL", "COPILOT_UPSTASH_SEARCH_REST_URL"],
  [
    "NEXT_PUBLIC_UPSTASH_SEARCH_REST_READONLY_TOKEN",
    "COPILOT_UPSTASH_SEARCH_REST_READONLY_TOKEN",
  ],
  ["BLOB_READ_WRITE_TOKEN", "COPILOT_BLOB_READ_WRITE_TOKEN"],
  ["COPILOT_DEV_EMAIL", "COPILOT_DEV_EMAIL"],
  ["COPILOT_DEV_PASS", "COPILOT_DEV_PASS"],
];

// Static values that are always safe for local / Copilot dev sessions.
const STATIC_VALUES = {
  NEXTAUTH_URL: "https://localhost:3000",
  NEXT_PUBLIC_BASE_URL: "https://localhost:3000",
  NODE_ENV: "development",
};

// ---------------------------------------------------------------------------
// Resolve values
// ---------------------------------------------------------------------------
const resolved = {};

for (const [key, sourceVar] of VARIABLE_MAP) {
  const value = process.env[sourceVar] ?? "";
  if (value) {
    resolved[key] = value;
  }
}

// Guard: DATABASE_URL is required for the dev server to start.
if (!resolved["DATABASE_URL"]) {
  console.warn(
    "⚠️  COPILOT_DATABASE_URL is not set — skipping .env.local generation.\n" +
      "   The Neon preview branch is likely not yet created for this PR.\n" +
      "   Re-run this script after the neon-branch workflow completes.",
  );
  process.exit(0);
}

// NEXTAUTH_SECRET: derive from DATABASE_URL so it's stable per-branch but
// never committed.
if (!resolved["NEXTAUTH_SECRET"]) {
  const raw = `dev-secret::${resolved["DATABASE_URL"]}`;
  resolved["NEXTAUTH_SECRET"] = Buffer.from(raw).toString("base64").slice(0, 44);
}

// ---------------------------------------------------------------------------
// Build file content
// ---------------------------------------------------------------------------
const lines = [
  "# Auto-generated by scripts/generate-env.mjs — do not edit manually.",
  "# Re-run `node scripts/generate-env.mjs` to refresh.",
  "",
];

for (const [key, value] of Object.entries(STATIC_VALUES)) {
  lines.push(`${key}=${value}`);
}

lines.push("");

for (const [key, value] of Object.entries(resolved)) {
  const needsQuotes = /[\s"'`$\\]/.test(value);
  lines.push(
    `${key}=${needsQuotes ? `"${value.replace(/"/g, '\\"')}"` : value}`,
  );
}

lines.push("");

const content = lines.join("\n");

writeFileSync(outputPath, content, "utf8");
console.log(`✅  Written ${outputPath}`);
